name: GitHub PHPUnit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql-server:
        image: mysql:5.7
        env:
          # MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: db_password
          MYSQL_DATABASE: db_name
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        id: composer-install
        # if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress
          # composer install --dev --no-autoloader --prefer-dist --no-progress symfony/phpunit-bridge

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Xdebug Action
        uses: MilesChou/docker-xdebug@master

      # Symfony
      # - name: Check the Symfony console
      #   run: |
      #     php bin/console -V
      #     php bin/console about

      - name: Run test suite
        id: phpunit
        env:
          #  JWT_SECRET: "${{ secrets.JWT_SECRET }}"
          XDEBUG_MODE: "coverage"
        run: |
          echo "${{ secrets.PUBLICA }}" >| ./config/jwt/public.pem;
          echo "${{ secrets.PRIVADA }}" >| ./config/jwt/private.pem;
          php -dxdebug.mode=coverage ./vendor/bin/simple-phpunit

      # https://github.com/phpstan/phpstan
      # - name: Analyse PHP Code (PHPStan)
      #   run: vendor/bin/phpstan analyse
